### PR TITLE
OnPress opacity changed

### PR DESCRIPTION
**Pull request by Shakarang**
Hey !

I've removed the opacity when you click on a TabIcon to look like the real iOS Tab Bar.

### CODE REVIEW

**Comment by aksonov** [comment]
Could we make it configurable? Some users may want opacity change.

**Comment by Shakarang** [comment]
For the moment no, I will do it later today.

**Comment by aksonov** [comment]
What is default opacity ? Will opacity work if no props is given?

**Comment by Shakarang** [comment]
The default opacity is 0.

Yes it works, I've just tried.

**Pull request merged**
